### ISSUE TITLE
Missing License File

### ISSUE THREAD

**Issue by paulreimer** [invertase/react-native-firebase-examples#3]
Noticed there is no LICENSE file or mention of acceptable use.

The default license (which is fine!) would be:
(From https://help.github.com/articles/licensing-a-repository/)

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

Even if that's the case though, it would be nice to have a LICENSE file reminding of that. There are some nice touches in the way this repo is setup though, it could really save some time in the setup of brand new projects!

**Comment by Ehesp** [comment]
Hey, sorry about that. We actually haven't really given this much attention due  to the work on the main library. I'll set one up tomorrow.

**Comment by Ehesp** [comment]
https://github.com/invertase/react-native-firebase-examples/commit/cc034018e6b27fec2b6fdb4dd863480ab02ec1a9
